# Adaptive Subject-Level Differential Privacy - Colab Runner

**Before running:** Go to `Runtime -> Change runtime type -> T4 GPU`.

This notebook clones the repo, installs dependencies, runs privacy/utility experiments, and saves every run as an iteration under `results/`.

## 1. Clone or Update the Repo

In [1]:
import os

repo_dir = '/content/ml-research'
if os.path.exists(repo_dir):
    %cd /content/ml-research
    !git pull
else:
    %cd /content
    !git clone https://github.com/shaktsin/ml-research.git
    %cd /content/ml-research

%cd /content/ml-research/adaptive-diff-privacy

/content
Cloning into 'ml-research'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 63 (delta 34), reused 38 (delta 17), pack-reused 0 (from 0)
Receiving objects: 100% (63/63), 34.99 KiB | 11.66 MiB/s, done.
Resolving deltas: 100% (34/34), done.
/content/ml-research
/content/ml-research/adaptive-diff-privacy

## 2. Install Dependencies

In [2]:
!pip install -q -r requirements.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.9/308.9 kB 11.9 MB/s eta 0:00:00

## 3. Verify GPU

In [3]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')
if device == 'cuda':
    print(f'GPU: {torch.cuda.get_device_name(0)}')

Device: cuda
GPU: Tesla T4

## 4. Run AG News Utility-Preserving Setting

This is the clean utility result: Adaptive Subject-DP should stay close to baseline accuracy and beat uniform Subject-DP on accuracy.

In [4]:
!python run_experiment.py --dataset ag_news --base-sigma 0.005 --mia-samples 500

Device: cuda
Config: lr=2e-05, batch_size=16, epochs=3, clip_norm=1.0, base_sigma=0.005, dataset=ag_news, iteration=1, max_train=2000, max_test=500, mia_samples=500, output_dir=results
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
tokenizer_config.json: 100% 48.0/48.0 [00:00<00:00, 183kB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 1.14MB/s]
tokenizer.json: 100% 466k/466k [00:00<00:00, 934kB/s]
Loading ag_news dataset...
README.md: 100% 8.07k/8.07k [00:00<00:00, 26.5MB/s]
data/train-00000-of-00001.parquet: 100% 18.6M/18.6M [00:01<00:00, 13.2MB/s]
data/test-00000-of-00001.parquet: 100% 1.23M/1.23M [00:00<00:00, 2.32MB/s]
Generating train split: 100% 120000/120000 [00:00<00:00, 676758.98 examples/s]
Generating test split: 100% 7600/7600 [00:00<00:00, 674582.27 examples/s]

============================================================
  Config: Baseline (no DP)
============================================================
config.json: 100% 483/483 [00:00<00:00, 2.44MB/s]
model.safetensors: 100% 268M/268M [00:01<00:00, 136MB/s]
[transformers] The following layers were not sharded: distilbert.transformer.layer.*.attention.q_lin.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.embeddings.position_embeddings.weight, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.q_lin.bias, pre_classifier.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.output_layer_norm.bias, pre_classifier.bias, distilbert.transformer.layer.*.ffn.lin1.weight, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.ffn.lin1.bias, classifier.bias, distilbert.embeddings.word_embeddings.weight, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.embeddings.LayerNorm.bias, classifier.weight, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.attention.k_lin.bias, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.transformer.layer.*.attention.v_lin.bias, distilbert.embeddings.LayerNorm.weight
Loading weights: 100% 100/100 [00:00<00:00, 9962.48it/s]
Baseline epoch 1: 100% 125/125 [00:21<00:00,  5.88it/s]
  Epoch 1 loss: 0.6946
Baseline epoch 2: 100% 125/125 [00:20<00:00,  6.02it/s]
  Epoch 2 loss: 0.2993
Baseline epoch 3: 100% 125/125 [00:21<00:00,  5.87it/s]
  Epoch 3 loss: 0.1749

  Results for [Baseline (no DP)]
    Accuracy : 0.8920
    MIA AUC  : 0.5687  (0.5=best privacy, 1.0=worst)

============================================================
  Config: Subject-DP (uniform noise)
============================================================
[transformers] The following layers were not sharded: distilbert.transformer.layer.*.attention.q_lin.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.embeddings.position_embeddings.weight, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.q_lin.bias, pre_classifier.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.output_layer_norm.bias, pre_classifier.bias, distilbert.transformer.layer.*.ffn.lin1.weight, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.ffn.lin1.bias, classifier.bias, distilbert.embeddings.word_embeddings.weight, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.embeddings.LayerNorm.bias, classifier.weight, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.attention.k_lin.bias, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.transformer.layer.*.attention.v_lin.bias, distilbert.embeddings.LayerNorm.weight
Loading weights: 100% 100/100 [00:00<00:00, 8565.05it/s]
Subject-DP epoch 1: 100% 125/125 [01:06<00:00,  1.87it/s]
  Epoch 1 loss: 1.2398
Subject-DP epoch 2: 100% 125/125 [01:06<00:00,  1.87it/s]
  Epoch 2 loss: 0.7922
Subject-DP epoch 3: 100% 125/125 [01:07<00:00,  1.86it/s]
  Epoch 3 loss: 0.5991

  Results for [Subject-DP (uniform noise)]
    Accuracy : 0.8380
    MIA AUC  : 0.5865  (0.5=best privacy, 1.0=worst)

============================================================
  Config: Adaptive Subject-DP (proposed)
============================================================
[transformers] The following layers were not sharded: distilbert.transformer.layer.*.attention.q_lin.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.embeddings.position_embeddings.weight, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.q_lin.bias, pre_classifier.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.output_layer_norm.bias, pre_classifier.bias, distilbert.transformer.layer.*.ffn.lin1.weight, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.ffn.lin1.bias, classifier.bias, distilbert.embeddings.word_embeddings.weight, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.embeddings.LayerNorm.bias, classifier.weight, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.attention.k_lin.bias, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.transformer.layer.*.attention.v_lin.bias, distilbert.embeddings.LayerNorm.weight
Loading weights: 100% 100/100 [00:00<00:00, 4876.98it/s]
Adaptive-DP epoch 1: 100% 125/125 [01:07<00:00,  1.87it/s]
  Epoch 1 loss: 1.1514
Adaptive-DP epoch 2: 100% 125/125 [01:07<00:00,  1.87it/s]
  Epoch 2 loss: 0.6745
Adaptive-DP epoch 3: 100% 125/125 [01:07<00:00,  1.86it/s]
  Epoch 3 loss: 0.5518

  Results for [Adaptive Subject-DP (proposed)]
    Accuracy : 0.8760
    MIA AUC  : 0.6036  (0.5=best privacy, 1.0=worst)

============================================================
  FINAL RESULTS SUMMARY
============================================================
  Config                                Accuracy    Raw MIA   MIA Risk
  --------------------------------------------------------------------
  Baseline (no DP)                        0.8920     0.5687     0.5687
  Subject-DP (uniform noise)              0.8380     0.5865     0.5865
  Adaptive Subject-DP (proposed)          0.8760     0.6036     0.6036

============================================================
  PAPER-READY TAKEAWAY
============================================================
  Adaptive Subject-DP preserves baseline-level utility: 0.8760 accuracy vs 0.8920 baseline (-0.0160).
  Adaptive Subject-DP improves utility over uniform Subject-DP: +0.0380 accuracy.
  Membership inference remains near random: raw AUC=0.6036, risk AUC=0.6036, attack advantage=0.2072.

  MIA AUC interpretation:
    Raw AUC near 0.50 means the attack is close to random guessing.
    Raw AUC below 0.50 is not better-than-perfect privacy; it means
    the attack direction is unstable, so MIA Risk reports max(AUC, 1-AUC).

  Saved iteration results:
    JSON: results/iteration_0001.json
    CSV : results/experiment_results.csv

## 5. Run IMDb Privacy Stress Test

IMDb is more useful for testing leakage because small training subsets and more epochs can make the baseline overfit. The result is automatically saved as the next iteration.

In [5]:
!python run_experiment.py --dataset imdb --max-train 500 --max-test 500 --epochs 8 --mia-samples 500 --base-sigma 0.005

Device: cuda
Config: lr=2e-05, batch_size=16, epochs=8, clip_norm=1.0, base_sigma=0.005, dataset=imdb, iteration=2, max_train=500, max_test=500, mia_samples=500, output_dir=results
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading imdb dataset...
README.md: 100% 7.81k/7.81k [00:00<00:00, 27.7MB/s]
plain_text/train-00000-of-00001.parquet: 100% 21.0M/21.0M [00:01<00:00, 17.9MB/s]
plain_text/test-00000-of-00001.parquet: 100% 20.5M/20.5M [00:00<00:00, 49.6MB/s]
plain_text/unsupervised-00000-of-00001.p(…): 100% 42.0M/42.0M [00:00<00:00, 54.6MB/s]
Generating train split: 100% 25000/25000 [00:00<00:00, 173084.33 examples/s]
Generating test split: 100% 25000/25000 [00:00<00:00, 147133.04 examples/s]
Generating unsupervised split: 100% 50000/50000 [00:00<00:00, 170477.99 examples/s]

============================================================
  Config: Baseline (no DP)
============================================================
[transformers] The following layers were not sharded: distilbert.embeddings.position_embeddings.weight, distilbert.transformer.layer.*.attention.q_lin.bias, distilbert.embeddings.word_embeddings.weight, classifier.weight, distilbert.embeddings.LayerNorm.bias, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.attention.k_lin.bias, pre_classifier.bias, distilbert.embeddings.LayerNorm.weight, distilbert.transformer.layer.*.output_layer_norm.bias, distilbert.transformer.layer.*.attention.v_lin.bias, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.ffn.lin1.weight, pre_classifier.weight, classifier.bias, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.ffn.lin1.bias, distilbert.transformer.layer.*.attention.q_lin.weight
Loading weights: 100% 100/100 [00:00<00:00, 5003.34it/s]
Baseline epoch 1: 100% 32/32 [00:05<00:00,  5.61it/s]
  Epoch 1 loss: 0.1984
Baseline epoch 2: 100% 32/32 [00:05<00:00,  5.78it/s]
  Epoch 2 loss: 0.0073
Baseline epoch 3: 100% 32/32 [00:05<00:00,  5.75it/s]
  Epoch 3 loss: 0.0028
Baseline epoch 4: 100% 32/32 [00:05<00:00,  5.71it/s]
  Epoch 4 loss: 0.0017
Baseline epoch 5: 100% 32/32 [00:05<00:00,  5.66it/s]
  Epoch 5 loss: 0.0011
Baseline epoch 6: 100% 32/32 [00:05<00:00,  5.62it/s]
  Epoch 6 loss: 0.0008
Baseline epoch 7: 100% 32/32 [00:05<00:00,  5.60it/s]
  Epoch 7 loss: 0.0006
Baseline epoch 8: 100% 32/32 [00:05<00:00,  5.60it/s]
  Epoch 8 loss: 0.0005

  Results for [Baseline (no DP)]
    Accuracy : 1.0000
    MIA AUC  : 0.5025  (0.5=best privacy, 1.0=worst)

============================================================
  Config: Subject-DP (uniform noise)
============================================================
[transformers] The following layers were not sharded: distilbert.embeddings.position_embeddings.weight, distilbert.transformer.layer.*.attention.q_lin.bias, distilbert.embeddings.word_embeddings.weight, classifier.weight, distilbert.embeddings.LayerNorm.bias, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.attention.k_lin.bias, pre_classifier.bias, distilbert.embeddings.LayerNorm.weight, distilbert.transformer.layer.*.output_layer_norm.bias, distilbert.transformer.layer.*.attention.v_lin.bias, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.ffn.lin1.weight, pre_classifier.weight, classifier.bias, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.ffn.lin1.bias, distilbert.transformer.layer.*.attention.q_lin.weight
Loading weights: 100% 100/100 [00:00<00:00, 5152.45it/s]
Subject-DP epoch 1: 100% 32/32 [00:16<00:00,  1.96it/s]
  Epoch 1 loss: 0.3998
Subject-DP epoch 2: 100% 32/32 [00:16<00:00,  1.93it/s]
  Epoch 2 loss: 0.0471
Subject-DP epoch 3: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 3 loss: 0.0087
Subject-DP epoch 4: 100% 32/32 [00:16<00:00,  1.96it/s]
  Epoch 4 loss: 0.0045
Subject-DP epoch 5: 100% 32/32 [00:16<00:00,  1.92it/s]
  Epoch 5 loss: 0.0031
Subject-DP epoch 6: 100% 32/32 [00:16<00:00,  1.96it/s]
  Epoch 6 loss: 0.0022
Subject-DP epoch 7: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 7 loss: 0.0017
Subject-DP epoch 8: 100% 32/32 [00:16<00:00,  1.95it/s]
  Epoch 8 loss: 0.0015

  Results for [Subject-DP (uniform noise)]
    Accuracy : 1.0000
    MIA AUC  : 0.4877  (0.5=best privacy, 1.0=worst)

============================================================
  Config: Adaptive Subject-DP (proposed)
============================================================
[transformers] The following layers were not sharded: distilbert.embeddings.position_embeddings.weight, distilbert.transformer.layer.*.attention.q_lin.bias, distilbert.embeddings.word_embeddings.weight, classifier.weight, distilbert.embeddings.LayerNorm.bias, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.attention.k_lin.bias, pre_classifier.bias, distilbert.embeddings.LayerNorm.weight, distilbert.transformer.layer.*.output_layer_norm.bias, distilbert.transformer.layer.*.attention.v_lin.bias, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.ffn.lin1.weight, pre_classifier.weight, classifier.bias, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.ffn.lin1.bias, distilbert.transformer.layer.*.attention.q_lin.weight
Loading weights: 100% 100/100 [00:00<00:00, 17594.30it/s]
Adaptive-DP epoch 1: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 1 loss: 0.4314
Adaptive-DP epoch 2: 100% 32/32 [00:16<00:00,  1.96it/s]
  Epoch 2 loss: 0.0514
Adaptive-DP epoch 3: 100% 32/32 [00:16<00:00,  1.91it/s]
  Epoch 3 loss: 0.0086
Adaptive-DP epoch 4: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 4 loss: 0.0042
Adaptive-DP epoch 5: 100% 32/32 [00:16<00:00,  1.95it/s]
  Epoch 5 loss: 0.0029
Adaptive-DP epoch 6: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 6 loss: 0.0021
Adaptive-DP epoch 7: 100% 32/32 [00:16<00:00,  1.96it/s]
  Epoch 7 loss: 0.0016
Adaptive-DP epoch 8: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 8 loss: 0.0013

  Results for [Adaptive Subject-DP (proposed)]
    Accuracy : 1.0000
    MIA AUC  : 0.4916  (0.5=best privacy, 1.0=worst)

============================================================
  FINAL RESULTS SUMMARY
============================================================
  Config                                Accuracy    Raw MIA   MIA Risk
  --------------------------------------------------------------------
  Baseline (no DP)                        1.0000     0.5025     0.5025
  Subject-DP (uniform noise)              1.0000     0.4877     0.5123
  Adaptive Subject-DP (proposed)          1.0000     0.4916     0.5084

============================================================
  PAPER-READY TAKEAWAY
============================================================
  Adaptive Subject-DP preserves baseline-level utility: 1.0000 accuracy vs 1.0000 baseline (+0.0000).
  Adaptive Subject-DP improves utility over uniform Subject-DP: +0.0000 accuracy.
  Membership inference remains near random: raw AUC=0.4916, risk AUC=0.5084, attack advantage=0.0167.

  MIA AUC interpretation:
    Raw AUC near 0.50 means the attack is close to random guessing.
    Raw AUC below 0.50 is not better-than-perfect privacy; it means
    the attack direction is unstable, so MIA Risk reports max(AUC, 1-AUC).

  Saved iteration results:
    JSON: results/iteration_0002.json
    CSV : results/experiment_results.csv

## 6. Run Stronger IMDb Privacy Setting

Use this to compare a stronger/noisier privacy setting against the previous iteration.

In [6]:
!python run_experiment.py --dataset imdb --max-train 500 --max-test 500 --epochs 8 --mia-samples 500 --base-sigma 0.01

Device: cuda
Config: lr=2e-05, batch_size=16, epochs=8, clip_norm=1.0, base_sigma=0.01, dataset=imdb, iteration=3, max_train=500, max_test=500, mia_samples=500, output_dir=results
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading imdb dataset...

============================================================
  Config: Baseline (no DP)
============================================================
[transformers] The following layers were not sharded: distilbert.embeddings.LayerNorm.bias, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.attention.k_lin.bias, classifier.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.transformer.layer.*.output_layer_norm.bias, classifier.bias, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.embeddings.LayerNorm.weight, distilbert.transformer.layer.*.ffn.lin1.bias, pre_classifier.weight, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.embeddings.position_embeddings.weight, pre_classifier.bias, distilbert.transformer.layer.*.attention.q_lin.weight, distilbert.embeddings.word_embeddings.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.ffn.lin1.weight, distilbert.transformer.layer.*.attention.q_lin.bias, distilbert.transformer.layer.*.attention.v_lin.bias
Loading weights: 100% 100/100 [00:00<00:00, 5149.48it/s]
Baseline epoch 1: 100% 32/32 [00:05<00:00,  5.47it/s]
  Epoch 1 loss: 0.1842
Baseline epoch 2: 100% 32/32 [00:05<00:00,  5.71it/s]
  Epoch 2 loss: 0.0061
Baseline epoch 3: 100% 32/32 [00:05<00:00,  5.67it/s]
  Epoch 3 loss: 0.0026
Baseline epoch 4: 100% 32/32 [00:05<00:00,  5.62it/s]
  Epoch 4 loss: 0.0016
Baseline epoch 5: 100% 32/32 [00:05<00:00,  5.60it/s]
  Epoch 5 loss: 0.0011
Baseline epoch 6: 100% 32/32 [00:05<00:00,  5.61it/s]
  Epoch 6 loss: 0.0008
Baseline epoch 7: 100% 32/32 [00:05<00:00,  5.61it/s]
  Epoch 7 loss: 0.0006
Baseline epoch 8: 100% 32/32 [00:05<00:00,  5.56it/s]
  Epoch 8 loss: 0.0004

  Results for [Baseline (no DP)]
    Accuracy : 1.0000
    MIA AUC  : 0.5190  (0.5=best privacy, 1.0=worst)

============================================================
  Config: Subject-DP (uniform noise)
============================================================
[transformers] The following layers were not sharded: distilbert.embeddings.LayerNorm.bias, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.attention.k_lin.bias, classifier.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.transformer.layer.*.output_layer_norm.bias, classifier.bias, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.embeddings.LayerNorm.weight, distilbert.transformer.layer.*.ffn.lin1.bias, pre_classifier.weight, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.embeddings.position_embeddings.weight, pre_classifier.bias, distilbert.transformer.layer.*.attention.q_lin.weight, distilbert.embeddings.word_embeddings.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.ffn.lin1.weight, distilbert.transformer.layer.*.attention.q_lin.bias, distilbert.transformer.layer.*.attention.v_lin.bias
Loading weights: 100% 100/100 [00:00<00:00, 20028.19it/s]
Subject-DP epoch 1: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 1 loss: 0.5513
Subject-DP epoch 2: 100% 32/32 [00:16<00:00,  1.91it/s]
  Epoch 2 loss: 0.1750
Subject-DP epoch 3: 100% 32/32 [00:17<00:00,  1.87it/s]
  Epoch 3 loss: 0.0269
Subject-DP epoch 4: 100% 32/32 [00:16<00:00,  1.91it/s]
  Epoch 4 loss: 0.0087
Subject-DP epoch 5: 100% 32/32 [00:16<00:00,  1.91it/s]
  Epoch 5 loss: 0.0052
Subject-DP epoch 6: 100% 32/32 [00:16<00:00,  1.93it/s]
  Epoch 6 loss: 0.0038
Subject-DP epoch 7: 100% 32/32 [00:16<00:00,  1.93it/s]
  Epoch 7 loss: 0.0029
Subject-DP epoch 8: 100% 32/32 [00:16<00:00,  1.89it/s]
  Epoch 8 loss: 0.0023

  Results for [Subject-DP (uniform noise)]
    Accuracy : 1.0000
    MIA AUC  : 0.4987  (0.5=best privacy, 1.0=worst)

============================================================
  Config: Adaptive Subject-DP (proposed)
============================================================
[transformers] The following layers were not sharded: distilbert.embeddings.LayerNorm.bias, distilbert.transformer.layer.*.sa_layer_norm.weight, distilbert.transformer.layer.*.attention.k_lin.bias, classifier.weight, distilbert.transformer.layer.*.attention.v_lin.weight, distilbert.transformer.layer.*.output_layer_norm.weight, distilbert.transformer.layer.*.output_layer_norm.bias, classifier.bias, distilbert.transformer.layer.*.attention.out_lin.bias, distilbert.embeddings.LayerNorm.weight, distilbert.transformer.layer.*.ffn.lin1.bias, pre_classifier.weight, distilbert.transformer.layer.*.sa_layer_norm.bias, distilbert.transformer.layer.*.ffn.lin2.bias, distilbert.transformer.layer.*.ffn.lin2.weight, distilbert.transformer.layer.*.attention.k_lin.weight, distilbert.embeddings.position_embeddings.weight, pre_classifier.bias, distilbert.transformer.layer.*.attention.q_lin.weight, distilbert.embeddings.word_embeddings.weight, distilbert.transformer.layer.*.attention.out_lin.weight, distilbert.transformer.layer.*.ffn.lin1.weight, distilbert.transformer.layer.*.attention.q_lin.bias, distilbert.transformer.layer.*.attention.v_lin.bias
Loading weights: 100% 100/100 [00:00<00:00, 4659.25it/s]
Adaptive-DP epoch 1: 100% 32/32 [00:16<00:00,  1.93it/s]
  Epoch 1 loss: 0.5123
Adaptive-DP epoch 2: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 2 loss: 0.1061
Adaptive-DP epoch 3: 100% 32/32 [00:16<00:00,  1.94it/s]
  Epoch 3 loss: 0.0145
Adaptive-DP epoch 4: 100% 32/32 [00:16<00:00,  1.90it/s]
  Epoch 4 loss: 0.0064
Adaptive-DP epoch 5: 100% 32/32 [00:16<00:00,  1.93it/s]
  Epoch 5 loss: 0.0041
Adaptive-DP epoch 6: 100% 32/32 [00:16<00:00,  1.92it/s]
  Epoch 6 loss: 0.0031
Adaptive-DP epoch 7: 100% 32/32 [00:16<00:00,  1.93it/s]
  Epoch 7 loss: 0.0024
Adaptive-DP epoch 8: 100% 32/32 [00:16<00:00,  1.92it/s]
  Epoch 8 loss: 0.0019

  Results for [Adaptive Subject-DP (proposed)]
    Accuracy : 1.0000
    MIA AUC  : 0.4893  (0.5=best privacy, 1.0=worst)

============================================================
  FINAL RESULTS SUMMARY
============================================================
  Config                                Accuracy    Raw MIA   MIA Risk
  --------------------------------------------------------------------
  Baseline (no DP)                        1.0000     0.5190     0.5190
  Subject-DP (uniform noise)              1.0000     0.4987     0.5013
  Adaptive Subject-DP (proposed)          1.0000     0.4893     0.5107

============================================================
  PAPER-READY TAKEAWAY
============================================================
  Adaptive Subject-DP preserves baseline-level utility: 1.0000 accuracy vs 1.0000 baseline (+0.0000).
  Adaptive Subject-DP improves utility over uniform Subject-DP: +0.0000 accuracy.
  Membership inference remains near random: raw AUC=0.4893, risk AUC=0.5107, attack advantage=0.0214.

  MIA AUC interpretation:
    Raw AUC near 0.50 means the attack is close to random guessing.
    Raw AUC below 0.50 is not better-than-perfect privacy; it means
    the attack direction is unstable, so MIA Risk reports max(AUC, 1-AUC).

  Saved iteration results:
    JSON: results/iteration_0003.json
    CSV : results/experiment_results.csv

## 7. Compare Saved Iterations

In [7]:
import pandas as pd

results_path = 'results/experiment_results.csv'
df = pd.read_csv(results_path)
display(df)

summary = df.pivot_table(
    index=['iteration', 'dataset', 'base_sigma', 'epochs', 'max_train', 'mia_samples'],
    columns='config',
    values=['accuracy', 'mia_risk_auc'],
    aggfunc='first',
)
display(summary)

,iteration,timestamp_utc,dataset,base_sigma,epochs,max_train,max_test,mia_samples,config,accuracy,raw_mia_auc,mia_risk_auc,mia_advantage,adaptive_accuracy_delta_vs_baseline,adaptive_accuracy_delta_vs_uniform_dp
0,1,2026-06-21T16:57:30.130440+00:00,ag_news,0.005,3,2000,500,500,Baseline (no DP),0.892,0.568716,0.568716,0.137432,-0.016,0.038
1,1,2026-06-21T16:57:30.130440+00:00,ag_news,0.005,3,2000,500,500,Subject-DP (uniform noise),0.838,0.586516,0.586516,0.173032,-0.016,0.038
2,1,2026-06-21T16:57:30.130440+00:00,ag_news,0.005,3,2000,500,500,Adaptive Subject-DP (proposed),0.876,0.603590,0.603590,0.207180,-0.016,0.038
3,2,2026-06-21T17:04:08.804117+00:00,imdb,0.005,8,500,500,500,Baseline (no DP),1.000,0.502536,0.502536,0.005072,0.000,0.000
4,2,2026-06-21T17:04:08.804117+00:00,imdb,0.005,8,500,500,500,Subject-DP (uniform noise),1.000,0.487744,0.512256,0.024512,0.000,0.000
5,2,2026-06-21T17:04:08.804117+00:00,imdb,0.005,8,500,500,500,Adaptive Subject-DP (proposed),1.000,0.491626,0.508374,0.016748,0.000,0.000
6,3,2026-06-21T17:10:44.539145+00:00,imdb,0.010,8,500,500,500,Baseline (no DP),1.000,0.518976,0.518976,0.037952,0.000,0.000
7,3,2026-06-21T17:10:44.539145+00:00,imdb,0.010,8,500,500,500,Subject-DP (uniform noise),1.000,0.498676,0.501324,0.002648,0.000,0.000
8,3,2026-06-21T17:10:44.539145+00:00,imdb,0.010,8,500,500,500,Adaptive Subject-DP (proposed),1.000,0.489282,0.510718,0.021436,0.000,0.000

                                                                                accuracy  \
config                                                    Adaptive Subject-DP (proposed)
iteration dataset base_sigma epochs max_train mia_samples
1         ag_news 0.005      3      2000      500                                  0.876
2         imdb    0.005      8      500       500                                  1.000
3         imdb    0.010      8      500       500                                  1.000

                                                                            \
config                                                    Baseline (no DP)
iteration dataset base_sigma epochs max_train mia_samples
1         ag_news 0.005      3      2000      500                    0.892
2         imdb    0.005      8      500       500                    1.000
3         imdb    0.010      8      500       500                    1.000

                                                                                      \
config                                                    Subject-DP (uniform noise)
iteration dataset base_sigma epochs max_train mia_samples
1         ag_news 0.005      3      2000      500                              0.838
2         imdb    0.005      8      500       500                              1.000
3         imdb    0.010      8      500       500                              1.000

                                                                            mia_risk_auc  \
config                                                    Adaptive Subject-DP (proposed)
iteration dataset base_sigma epochs max_train mia_samples
1         ag_news 0.005      3      2000      500                               0.603590
2         imdb    0.005      8      500       500                               0.508374
3         imdb    0.010      8      500       500                               0.510718

                                                                            \
config                                                    Baseline (no DP)
iteration dataset base_sigma epochs max_train mia_samples
1         ag_news 0.005      3      2000      500                 0.568716
2         imdb    0.005      8      500       500                 0.502536
3         imdb    0.010      8      500       500                 0.518976


config                                                    Subject-DP (uniform noise)
iteration dataset base_sigma epochs max_train mia_samples
1         ag_news 0.005      3      2000      500                           0.586516
2         imdb    0.005      8      500       500                           0.512256
3         imdb    0.010      8      500       500                           0.501324

## 8. Paper Claim Checklist

Look for this pattern before using a run in the paper:

- Baseline has high accuracy but MIA Risk is meaningfully above random on the leakage stress test.
- Uniform Subject-DP lowers MIA Risk but loses accuracy.
- Adaptive Subject-DP has similar MIA Risk to uniform Subject-DP with higher accuracy.

The final written claim should be: Adaptive Subject-DP improves the privacy-utility tradeoff by preserving more utility than uniform Subject-DP at comparable membership inference risk.